Added mergeSort, combSort, pancakeSort in Golang
VAR-solutions/Algorithms pull request #1330
Opened 2020-10-02 08:38 UTC by itsanshulverma

Issue #1122 

### Sorting algos in Go
- mergeSort
- combSort
- pancakeSort

@i-vishi please review this PR

2020-10-05 02:44 UTC, i-vishi requested changes

2020-10-05 02:44 UTC, i-vishi commented on Sorting/Merge Sort/Go/mergeSort.go
> +    fmt.Println("\nSelection Sort:")
Update the print statement by Merge sort

2020-10-05 03:31 UTC, itsanshulverma commented
Done with the changes. Sorry for the silly typo.
Please review and merge the pull request.

2020-10-05 04:12 UTC, itsanshulverma commented on Sorting/Merge Sort/Go/mergeSort.go
> +    fmt.Println("\nSelection Sort:")
Done with the changes. Sorry for the silly typo.
Please review and merge the pull request.

@i-vishi

2020-10-07 02:51 UTC, i-vishi approved these changes

2020-10-07 02:52 UTC, merged