Added code for vertical order traversal of a tree | C++
VAR-solutions/Algorithms pull request #1368
Opened 2020-10-02 13:33 UTC by GunjanMA

I've added the code for vertical order traversal of a binary tree in the traversals folder. Kindly merge my pull request.

2020-10-03 07:36 UTC, i-vishi requested changes
Current code is incomplete(No header files, tree struct is commented out, no definition of BuildTree function, etc.). Make necessary changes

2020-10-03 09:23 UTC, GunjanMA commented
> Current code is incomplete(No header files, tree struct is commented out, no definition of BuildTree function, etc.). Make necessary changes

I left it upon the user to define the BuildTree() as per his convenience.... anyways I'll add it now

2020-10-03 10:06 UTC, GunjanMA commented
did the required changes... Kindly merge this PR

2020-10-14 05:33 UTC, i-vishi approved these changes

2020-10-14 05:34 UTC, merged